"""
Languages and Locale Mappings for AetherTranslate Python Engine.
"""

SUPPORTED_LANGUAGES = {
    "auto": "Auto Detect",
    "en": "English",
    "es": "Spanish",
    "fr": "French",
    "de": "German",
    "it": "Italian",
    "pt": "Portuguese",
    "ru": "Russian",
    "zh-CN": "Chinese (Simplified)",
    "zh-TW": "Chinese (Traditional)",
    "ja": "Japanese",
    "ko": "Korean",
    "ar": "Arabic",
    "hi": "Hindi",
    "bn": "Bengali",
    "pa": "Punjabi",
    "ur": "Urdu",
    "nl": "Dutch",
    "tr": "Turkish",
    "pl": "Polish",
    "sv": "Swedish",
    "no": "Norwegian",
    "da": "Danish",
    "fi": "Finnish",
    "vi": "Vietnamese",
    "th": "Thai",
    "id": "Indonesian",
    "ms": "Malay",
    "he": "Hebrew",
    "el": "Greek",
    "cs": "Czech",
    "ro": "Romanian",
    "hu": "Hungarian",
    "uk": "Ukrainian",
    "fa": "Persian",
    "sw": "Swahili",
    "ta": "Tamil",
    "te": "Telugu"
}

# Locale mapping for Speech Recognition & Text-to-Speech (gTTS / BCP-47)
LOCALE_MAP = {
    "ur": "ur-PK",
    "pa": "pa-IN",
    "hi": "hi-IN",
    "ar": "ar-SA",
    "en": "en-US",
    "es": "es-ES",
    "fr": "fr-FR",
    "de": "de-DE",
    "it": "it-IT",
    "pt": "pt-PT",
    "ru": "ru-RU",
    "zh-CN": "zh-CN",
    "zh-TW": "zh-TW",
    "ja": "ja-JP",
    "ko": "ko-KR",
    "bn": "bn-IN",
    "nl": "nl-NL",
    "tr": "tr-TR",
    "pl": "pl-PL",
    "sv": "sv-SE",
    "no": "no-NO",
    "da": "da-DK",
    "fi": "fi-FI",
    "vi": "vi-VN",
    "th": "th-TH",
    "id": "id-ID",
    "ms": "ms-MY",
    "he": "he-IL",
    "el": "el-GR",
    "cs": "cs-CZ",
    "ro": "ro-RO",
    "hu": "hu-HU",
    "uk": "uk-UA",
    "fa": "fa-IR",
    "sw": "sw-KE",
    "ta": "ta-IN",
    "te": "te-IN"
}
